name: "Setup JuleC environment"
description: "Setup a JuleC development environment in your project."
author: "Panquesito7"
branding:
  icon: code
  color: gray-dark
inputs:
  version:
    description: "The version of JuleC that will be downloaded. Use \"latest\" for the latest Git version."
    required: true
    default: "latest"
  directory:
    description: "Directory where Jule will be downloaded."
    required: true
    default: "."
  architecture:
    description: "The architecture that's going to be used. Valid options are \"arm64\" and \"amd64\"."
    required: false
    default: "amd64"
  add-to-path:
    description: "Whether to add JuleC to the PATH or not."
    required: false
    default: "false"
  extra-command:
    description: "Extra command that will be executed after JuleC is installed."
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y wget tar
    - name: Adjust directory
      shell: bash
      run: |
        directory="${{ inputs.directory }}"
        if [[ ${{ inputs.directory }} == */ ]]; then
          directory="${directory%?}"
          ${{ inputs.directory }}=directory
        fi
    - name: Clone JuleC
      shell: bash
      run: |
        if [[ ${{ inputs.version }} == "latest" ]] || [[ ${{ inputs.version }} == "current" ]]; then
          git clone https://github.com/julelang/jule.git ${{ inputs.directory }}/julec-${{ inputs.version }}
        else
          wget https://github.com/julelang/jule/archive/refs/tags/jule-${{ inputs.version }}.tar.gz -O julec.tar.gz
          tar -xzf julec.tar.gz -C ${{ inputs.directory }}/julec-${{ inputs.version }}
        fi
    - name: Get JuleC IR
      shell: bash
      run: |
        cd ${{ inputs.directory }}/julec-${{ inputs.version }}
        wget https://raw.githubusercontent.com/julelang/julec-ir/main/src/linux-${{ inputs.architecture }}.cpp -O ir.cpp
    - name: Compile JuleC
      shell: bash
      run: |
        cd ${{ inputs.directory }}/julec-${{ inputs.version }}
        mkdir bin
        clang++ -O0 --std=c++17 -Wno-everything -o bin/julec ir.cpp
    - name: Add JuleC to the PATH
      shell: bash
      run: |
        if [[ ${{ inputs.add-to-path }} == true ]]; then
          echo "export PATH=\$PATH:${{ inputs.directory }}/julec-${{ inputs.version }}/bin/" >> $GITHUB_PATH
        fi
    - name: Run extra commands
      shell: bash
      run: |
        if [[ -n "${{ inputs.extra-command }}" ]]; then
          if [[ ${{ inputs.add-to-path }} == true ]]; then
            julec ${{ inputs.extra-command }}
          else
            ${{ inputs.directory }}/julec-${{ inputs.version }}/bin/julec ${{ inputs.extra-command }}
          fi
        fi
