name: Action validation
on: workflow_dispatch
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Jule
        uses: Panquesito7/setup-jule@windows_support
        with:
          version: dev
          directory: .
          add-to-path: true
          architecture: amd64
          extra-command: version
