name: Action validation
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Jule
        uses: Panquesito7/setup-jule@main
        with:
          version: dev
          directory: .
          add-to-path: true
          architecture: amd64
          extra-command: version
